apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: k8
  labels:
    app: nginx1-dep
spec:
  replicas: 3  # Number of desired pod replicas
  selector:
    matchLabels:
      app: nginx1-dep
  template:
    metadata:
      labels:
        app: nginx1-dep  # Must match the selector above
    spec:
      containers:
      - name: nginx
        image: nginx:1.18
        ports:
        - containerPort: 80