apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: k8
  labels:
    app: nginx1-dep
spec:
  type: LoadBalancer   # Default; can be omitted
  selector:
    app: nginx1-dep
  ports:
    - protocol: TCP
      port: 80         # Service port inside the cluster
      targetPort: 80   # Container port